### ISSUE TITLE
Migrate website to hosted solution

### ISSUE THREAD

**Issue by KiwiInNZ** [wxcapture/wxcapture#2]
Putting  the website part onto a cloud server – AWS or similar

**Comment by KiwiInNZ** [comment]
The webserver component now sits on a VM, which will assist in this migration.

**Comment by technobird22** [comment]
I will try running the WxCapture server myself once I set one up. That way, we can emulate having a remote server and @KiwiInNZ could try some other things like feeding to a remote server, and more.

**Comment by KiwiInNZ** [comment]
This is already in place.

**Comment by KiwiInNZ** [comment]
This is already in place.
