### ISSUE TITLE
Create PoI (Points of Interest) page(s) on website

### ISSUE THREAD

**Issue by KiwiInNZ** [wxcapture/wxcapture#20]
Create pages to highlight points of interest seen on images for different satellite types.

This could include:
- Locations - around NZ / surrounding areas covered
- Events, e.g. volcano eruptions, interesting cloud features, bush fire smoke clouds

**Comment by technobird22** [comment]
This will be an ongoing task as more PoIs (Points of interest) are found and added.
Some first steps already done include: 
- Creating a list of PoIs
- Find existing PoIs. These are currently stored on a word document.

Some future steps include:
- Locating and aggregating more PoIs
- Put PoIs in organised directories 
- Having a popup modal window where more information about a PoI can be found. There will also be numerous sample image crops of the PoI (see below).
- Finding multiple instances of PoIs that can be added into the modal.

**Comment by KiwiInNZ** [comment]
Closing as unlikely to be implemented in the near future.
