### ISSUE TITLE
Capture page update - multi-tabs

### ISSUE THREAD

**Issue by KiwiInNZ** [wxcapture/wxcapture#21]
Update the captures page to display multiple images using multiple tabs to replace (or complement?) the existing modal window display of images for a pass.

**Comment by technobird22** [comment]
- Frontend is mostly done, just need a pass selector
https://wxcapture.github.io/wxcapture/server-website/wxcapture/passes.html
- Now just need to use some JS to automatically read the JSON files and get the images.
