### ISSUE TITLE
Remove ".html" from the page URLs

### ISSUE THREAD

**Issue by technobird22** [wxcapture/wxcapture#31]
Remove `.html` part from the end of page URLs.
Eg, instead of having https://kiwiweather.com/satpass.html, switch to https://kiwiweather.com/satpass

**Comment by KiwiInNZ** [comment]
Discussion of how to do this is at - https://stackoverflow.com/questions/5730092/how-to-remove-html-from-url

**Comment by KiwiInNZ** [comment]
This is a vanity change which has the potential to impact other areas of functionality, so no proceeding.
