### ISSUE TITLE
Discord webhook shows wrong pass time

### ISSUE THREAD

**Issue by technobird22** [wxcapture/wxcapture#32]
WxCapture discord webhook clearly shows the wrong pass time.

![image](https://user-images.githubusercontent.com/51074275/82721384-c944fa80-9d10-11ea-9a35-1dae68dc57c2.png)
![image](https://user-images.githubusercontent.com/51074275/82721394-d661e980-9d10-11ea-8136-98b3ba4b9bb2.png)
![image](https://user-images.githubusercontent.com/51074275/82721399-dbbf3400-9d10-11ea-99de-c8d933d4ed95.png)

**Comment by KiwiInNZ** [comment]
Bug found in wxcutils_pi.webhooks where some debug code had been left in.

Code updated and works in testing.
