### ISSUE TITLE
Meteor Image not appearing on Discord webhook

### ISSUE THREAD

**Issue by technobird22** [wxcapture/wxcapture#36]
### Meteor Image not appearing on Discord webhook
![image](https://user-images.githubusercontent.com/51074275/83195320-2962f300-a18e-11ea-92d4-ac8f207c6970.png)
![image](https://user-images.githubusercontent.com/51074275/83195339-2f58d400-a18e-11ea-8e43-af989f41fb5d.png)
### When clearly the image exists:
![image](https://user-images.githubusercontent.com/51074275/83195373-3c75c300-a18e-11ea-8e46-82f868037299.png)

**Comment by KiwiInNZ** [comment]
Resolved with a delay / check loop that waits for the image to be on the webserver and accessible at the URL that the webhook will used, waiting up for 10 minutes maximum.
