### ISSUE TITLE
Past captures of satellite not currently being captured show up as "???"

### ISSUE THREAD

**Issue by technobird22** [wxcapture/wxcapture#38]
Past captures of satellite not currently being captured show up as "???"

NOAA9:
![image](https://user-images.githubusercontent.com/51074275/85189984-09939a80-b308-11ea-948e-e654ea46acb2.png)

**Comment by KiwiInNZ** [comment]
Fixed - satellites which have been captured must never be totally removed from satellites.json, they must instead be set to active: no.
The reason for this is that this json file is used to build the link name, so if no entry it shows as ???.
