### ISSUE TITLE
Combine passes to produce animation

### ISSUE THREAD

**Issue by technobird22** [wxcapture/wxcapture#40]
Next step from enhancement #8 
Example of this in action: https://www.reddit.com/r/amateursatellites/comments/gm8f70/timelapse_from_all_the_noaa_images_i_received/?utm_source=share&utm_medium=web2x

I have contacted the author and got the code for generating the animations.

**Comment by technobird22** [comment]
Code reddit author used: https://github.com/pausrn/NOAA_timelapse

**Comment by KiwiInNZ** [comment]
Not intending to implement this feature.
