### ISSUE TITLE
After installing files how to get web server going?

### ISSUE THREAD

**Issue by jeffreypkelly** [wxcapture/wxcapture#44]
I don't understand how to get from installing everything to working system.

I am getting an error in the schedule_satellites:
2021-02-22 08:55:50,411 - schedule_passes - DEBUG - tle file does not exist - /home/pi/wxcapture/process/working/ deltat.data - replacing with backup
2021-02-22 08:55:50,413 - schedule_passes - DEBUG - copy_file from /home/pi/wxcapture/process/working//deltat.data.old to /home/pi/wxcapture/process/working//deltat.data
2021-02-22 08:55:50,416 - schedule_passes - CRITICAL - Global exception handler: <class 'FileNotFoundError'> [Errno 2] No such file or directory: '/home/pi/wxcapture/process/working//deltat.data.old' <traceback object at 0x6fd3b788>
2

weather.tle is present in the working folder. Not sure what delta.data is??

I installed Apache2 on the Pi - how do I tell wxcapture that it is there?

**Comment by KiwiInNZ** [comment]
The deltat.data file (and some others) should be created by update_planets_tle.py which should be running via a cron job (once a day, just after midnight) plus you can run it manually. If schedule_satellites.py runs before this has run, you'll see this error.

For Apache2 (or another web server), the location where your files will be written to are held in config.json which is in the ~/wxcapture/process/config/ directory.

Edit this file and update the following line:
`"web doc root location": "/home/websites/wxcapture/",`
You'll need to update the location to where your web server folder is, which will vary depending on your linux distribution and if you've done anything to change this.

https://www.google.com/search?q=apache2+document+root

This should help you find where it should be for your installation, but a good starting place is likely to be:
`/var/www/html`

**Comment by jeffreypkelly** [comment]
I assume I can run update_planets_tle now, but that didn't create the file.
I also don't have that line in my config.json.
Perhaps I am in over my head. I'll try again in the future.
TY!

**Comment by KiwiInNZ** [comment]
1. I got a very, very similar output when I ran the script on my Pi! I've updated this script which is now available on GitHub (just overwrite your existing file with this one). It will now gracefully handle this problem whilst I find a long term fix. However the issue won't stop the main application working as intended (as you can see from kiwiweather.com)

2. https://github.com/wxcapture/wxcapture/blob/master/server-code/wxcapture/web/config/config.json
This shows what the file should look like and where it is. You'll also be able to navigate around the expected directory structure to see what is missing / incorrect.

Also check that you're looking on the webserver as there is a config.json file when you're looking at the pi which does the capture.

**Comment by KiwiInNZ** [comment]
Current issue with update_planets.py:
* de421.bsp - downloads and validates
* deltat.data, deltat.preds, Leap_Second.dat - not downloading via library

Library = skyfield.api

**Comment by KiwiInNZ** [comment]
https://pypi.org/project/skyfield-data/

> Deprecation warning: As of python-skyfield>=1.31, Leap_Second.dat, deltat.data and deltat.preds files are not used anymore.

I've now removed the updating / validation of these files from update_planets.py, with the new version uploaded to GitHub.

This fully explains why there were no impact from the script errors as originally reported.

Thank you for reporting this issue.
