### ISSUE TITLE
Combine multiple pass images into an overlay

### ISSUE THREAD

**Issue by KiwiInNZ** [wxcapture/wxcapture#8]
Currently each pass for NOAA 15 / 18 / 19 (and Meteor M-2) is an individual image.

Where there are multiple passes, which happens each morning / evening, these can be combined in a single image, per satellite type (NOAA / Meteor) to produce a mosaic image covering an extended area.

**Comment by KiwiInNZ** [comment]
To create overlays, need to create files as .png files directly from wxtoimg as they contain image header tags which includes the pass information.

So far it seems that any image type can be used for this process.

E.g.
wxtoimg -o -I -A -e MCIR-precip -m /home/pi/wxcapture/output/images/2020-05-11-09-17-39-NOAA_18-map.png /home/pi/wxcapture/audio/2020-05-11-09-17-39-NOAA_18.wav 2020-05-11-09-17-39-NOAA_18-mcir-precip.png
and
wxtoimg -o -I -A -e MCIR-precip -m /home/pi/wxcapture/output/images/2020-05-11-10-58-36-NOAA_18-map.png /home/pi/wxcapture/audio/2020-05-11-10-58-36-NOAA_18.wav 2020-05-11-10-58-36-NOAA_18-mcir-precip.png

create the projection:
wxproj -o -S -p Eckert4 -l -37.050 -m 174.896 -b 0,-80,140,-150 -s 1 ./2020-05-11-09-17-39-NOAA_18-mcir-precip.png ./2020-05-11-09-17-39-NOAA_18-mcir-precip-proj.png
and
wxproj -o -S -p Eckert4 -l -37.050 -m 174.896 -b 0,-80,140,-150 -s 1 ./2020-05-11-10-58-36-NOAA_18-mcir-precip.png ./2020-05-11-10-58-36-NOAA_18-mcir-precip-proj.png

Note:
- there are other projects, as listed by typing wxproj.
- the bounding box (-b) is set using actual long/lat values which should be centered around the download site and should be large enough to include all passes

Then use imagemagic on each file to create a transparent image:
convert ./2020-05-11-09-17-39-NOAA_18-mcir-precip-proj.png -transparent 'Rgb(0,0,0)' ./2020-05-11-09-17-39-NOAA_18-mcir-precip-trans-proj.png
and
convert ./2020-05-11-10-58-36-NOAA_18-mcir-precip-proj.png -transparent 'Rgb(0,0,0)' ./2020-05-11-10-58-36-NOAA_18-mcir-precip-trans-proj.png

Then combine into the final image:
convert ./2020-05-11-09-17-39-NOAA_18-mcir-precip-trans-proj.png ./2020-05-11-10-58-36-NOAA_18-mcir-precip-trans-proj.png -evaluate-sequence Max -trim final-mcir-precip=ptC.png

Note:
- they are combined in the order listed
- combining images over multiple hours results in noticeable drift of clouds

Seems best to combine images:
- close in time
- covering different, overlapping areas (which minimizes alignment issues and creates the largest combined image)

**Comment by KiwiInNZ** [comment]
Functionality added to allow projections for NOAA passes.

Limited to combining two images from two(+) passes of the same satellite in the same morning / evening, otherwise alignment issues make the resultant image look poor.

This can be enabled on a per image enhancement basis, although since there is a significant computational overhead for creating projections, turning it on for multiple enhancements impacts performance.

Also added temperature scales for enhancement types which use them.

**Comment by KiwiInNZ** [comment]
It may be possible to get this approach working for Meteor images using wxproj, but will require, if it will work, Meteor images to be converted to .bmp images and image header tags added to match what are added by wxtoimg as these are used by wxproj to perform the projection calculations, including accessing the .tle data file.

**Comment by technobird22** [comment]
Could improve by overlaying one image more at a time, to get "animations" of moving clouds.

**Comment by technobird22** [comment]
Example: https://www.reddit.com/r/amateursatellites/comments/gm8f70/timelapse_from_all_the_noaa_images_i_received/?utm_source=share&utm_medium=web2x

**Comment by technobird22** [comment]
Code Reddit author used: https://github.com/pausrn/NOAA_timelapse

**Comment by technobird22** [comment]
### Next steps:
- Create animations using the data (New issue created: #40 )
- Combine meteor passes, as mentioned above by @KiwiInNZ:
> It may be possible to get this approach working for Meteor images using wxproj, but will require, if it will work, Meteor images to be converted to .bmp images and image header tags added to match what are added by wxtoimg as these are used by wxproj to perform the projection calculations, including accessing the .tle data file.

**Comment by KiwiInNZ** [comment]
Not intending to implement this for Meteor. This is already in place for NOAA.
